version: '3.5'

## PhotoPrism Stack Configuration for Portainer
services:
  photoprism:
    image: photoprism/photoprism:latest
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ## Server port mapping in the format "Host:Container". To use a different port, change the host port on
    ## the left-hand side and keep the container port, e.g. "80:2342" (for HTTP) or "443:2342 (for HTTPS):
    ports:
      - "2342:2342"
    ## Changes to the config options in stack.env always require a restart to take effect:
    ## https://docs.photoprism.app/getting-started/config-options/
    environment:
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
      - MARIADB_INITDB_SKIP_TZINFO=${MARIADB_INITDB_SKIP_TZINFO}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - PHOTOPRISM_DATABASE_DRIVER=${PHOTOPRISM_DATABASE_DRIVER}
      - PHOTOPRISM_DATABASE_SERVER=${PHOTOPRISM_DATABASE_SERVER}
      - PHOTOPRISM_DATABASE_NAME=${PHOTOPRISM_DATABASE_NAME}
      - PHOTOPRISM_DATABASE_USER=${PHOTOPRISM_DATABASE_USER}
      - PHOTOPRISM_DATABASE_PASSWORD=${PHOTOPRISM_DATABASE_PASSWORD}
      - PHOTOPRISM_ADMIN_USER=${PHOTOPRISM_ADMIN_USER}
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_ADMIN_PASSWORD}
      - PHOTOPRISM_AUTH_MODE=${PHOTOPRISM_AUTH_MODE}
      - PHOTOPRISM_SITE_URL=${PHOTOPRISM_SITE_URL}
      - PHOTOPRISM_DISABLE_TLS=${PHOTOPRISM_DISABLE_TLS}
      - PHOTOPRISM_DEFAULT_TLS=${PHOTOPRISM_DEFAULT_TLS}
      - PHOTOPRISM_ORIGINALS_LIMIT=${PHOTOPRISM_ORIGINALS_LIMIT}
      - PHOTOPRISM_HTTP_COMPRESSION=${PHOTOPRISM_HTTP_COMPRESSION}
      - PHOTOPRISM_LOG_LEVEL=${PHOTOPRISM_LOG_LEVEL}
      - PHOTOPRISM_READONLY=${PHOTOPRISM_READONLY}
      - PHOTOPRISM_EXPERIMENTAL=${PHOTOPRISM_EXPERIMENTAL}
      - PHOTOPRISM_DISABLE_CHOWN=${PHOTOPRISM_DISABLE_CHOWN}
      - PHOTOPRISM_DISABLE_WEBDAV=${PHOTOPRISM_DISABLE_WEBDAV}
      - PHOTOPRISM_DISABLE_SETTINGS=${PHOTOPRISM_DISABLE_SETTINGS}
      - PHOTOPRISM_DISABLE_TENSORFLOW=${PHOTOPRISM_DISABLE_TENSORFLOW}
      - PHOTOPRISM_DISABLE_FACES=${PHOTOPRISM_DISABLE_FACES}
      - PHOTOPRISM_DISABLE_CLASSIFICATION=${PHOTOPRISM_DISABLE_CLASSIFICATION}
      - PHOTOPRISM_DISABLE_VECTORS=${PHOTOPRISM_DISABLE_VECTORS}
      - PHOTOPRISM_DISABLE_RAW=${PHOTOPRISM_DISABLE_RAW}
      - PHOTOPRISM_RAW_PRESETS=${PHOTOPRISM_RAW_PRESETS}
      - PHOTOPRISM_JPEG_QUALITY=${PHOTOPRISM_JPEG_QUALITY}
      - PHOTOPRISM_DETECT_NSFW=${PHOTOPRISM_DETECT_NSFW}
      - PHOTOPRISM_UPLOAD_NSFW=${PHOTOPRISM_UPLOAD_NSFW}
      - PHOTOPRISM_SITE_CAPTION=${PHOTOPRISM_SITE_CAPTION}
      - PHOTOPRISM_SITE_DESCRIPTION=${PHOTOPRISM_SITE_DESCRIPTION}
      - PHOTOPRISM_SITE_AUTHOR=${PHOTOPRISM_SITE_AUTHOR}
    working_dir: "/photoprism" # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "/mnt/samba/AppData/PepePepeFotos/originals:/photoprism/originals" # Originals mount path can be changed as needed (DO NOT REMOVE)
      - "/mnt/samba/AppData/PepePepeFotos/storage:/photoprism/storage"     # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
      - "/mnt/samba/Datos Familia/Fotos:/photoprism/import"

  mariadb:
    image: mariadb:11
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "/home/pi/database:/var/lib/mysql" # DO NOT REMOVE
    environment:
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
      - MARIADB_INITDB_SKIP_TZINFO=${MARIADB_INITDB_SKIP_TZINFO}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    deploy:
      placement:
        constraints:
          - node.hostname == webhost.tech.eus
