version: '3.3'

services:
  r3_db:
    container_name: r3.7_db
    environment:
        POSTGRES_PASSWORD: app
        POSTGRES_USER: app
    image: postgres:latest
    restart: always
    volumes:
        - /root/rey/data_db:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname == webhost.tech.eus
  r3:
    container_name: r3.7.3_app
    image: "naielv/rei3:3.7.3"
    depends_on:
        - r3_db
    ports:
        - "14000:80"
    restart: always
    volumes:
        - /root/rey/data_app:/opt/r3/data
    deploy:
      placement:
        constraints:
          - node.hostname == webhost.tech.eus