version: '3.3'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2024.1.6 # There is a bug in newer versions becaouse of a bump in AwesomeVersion
    ports:
     - 8123:8123
    volumes:
     - /srv/mergerfs/Margaret/AppData/homeassistant/config:/config
     - /etc/localtime:/etc/localtime:ro
     - /home/pi/AppData/homeassistant-db:/dastabasefolder
    network_mode: "host"
  nodered:
    image: nodered/node-red:3.1.6-18
    user: root
    environment:
      TZ: Europe/Madrid
    ports:
     - 1886:1880
    volumes:
     - /srv/mergerfs/Margaret/AppData/node-red/data:/data
  wyoming-whisper:
    ports:
      - 10300:10300
    image: rhasspy/wyoming-whisper:2.1.0
    command: --model tiny-int8 --language es
  wyoming-piper:
    ports:
      - 10200:10200
    image: rhasspy/wyoming-piper:1.5.0
    command: --voice es_ES-sharvard-medium
  wyoming-openwakeword:
    ports:
      - 10400:10400
    image: rhasspy/wyoming-openwakeword:1.10.0
    command: --preload-model 'alexa'
  metube:
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /srv/mergerfs/Margaret/Media/Descargas YT:/downloads
      - /home/pi/AppData/metube_state_dir:/state_dir
    environment:
      - 'STATE_DIR=/state_dir'
      - 'YTDL_OPTIONS={"writesubtitles":true,"subtitleslangs":["en","es","-live_chat"],"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"SponsorBlock","categories":["sponsor"]},{"key":"ModifyChapters","remove_sponsor_segments":["sponsor"]},{"key":"FFmpegMetadata","add_chapters":true},{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"}]}'
      - 'OUTPUT_TEMPLATE=%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S - %(title|UNKNOWN_TITLE)S - %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S.%(ext)s'
