version: '2'


services:
  db:
    image: mariadb:11.3
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /home/pi/AppData/nextcloud4/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=decalelitismskillethatchet
      - MYSQL_PASSWORD=decalelitismskillethatchet
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8887:80
    links:
      - db
    volumes:
      - /srv/mergerfs/Margaret/AppData/nextcloud4:/var/www/html
    environment:
      - MYSQL_PASSWORD=decalelitismskillethatchet
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
