version: '2'


services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /home/pi/AppData/nextcloud4/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=decalelitismskillethatchet
      - MYSQL_PASSWORD=decalelitismskillethatchet
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8887:80
    links:
      - db
    volumes:
      - /srv/mergerfs/Margaret/AppData/nextcloud4:/var/www/html
      - /srv/mergerfs/Margaret:/margaretstorage
    environment:
      - MYSQL_PASSWORD=decalelitismskillethatchet
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  metube:
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /srv/mergerfs/Margaret/Media/Descargas YT:/downloads
      - /home/pi/AppData/metube_state_dir:/state_dir
    environment:
      - 'STATE_DIR=/state_dir'
      - 'YTDL_OPTIONS={"writesubtitles":true,"subtitleslangs":["en","es","-live_chat"],"updatetime":false,"postprocessors":[{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"},{"key":"SponsorBlock","categories":["sponsor"]},{"key":"ModifyChapters","remove_sponsor_segments":["sponsor"]},{"key":"FFmpegMetadata","add_chapters":true},{"key":"Exec","exec_cmd":"chmod 0664","when":"after_move"}]}'
      - 'OUTPUT_TEMPLATE=%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S - %(title|UNKNOWN_TITLE)S - %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S.%(ext)s'
