version: '3'
services:
  go2rtc:
    image: alexxit/go2rtc
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    volumes:
      - "/mnt/go2rtc:/config"